version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: dual-job-date-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DualJobDate
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - dual-job-date-network

  dual-job-date-api:
    image: dualjobdateapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AppDebugConnection: "Server=dual-job-date-db; Port=3306; Database=DualJobDate; Uid=root; Pwd=root;"
    depends_on:
      - mysql-db
    networks:
      - dual-job-date-network

networks:
  dual-job-date-network:
    driver: bridge
