version: '3.8'

services:
  DualJobDate-Api:
    image: dualjobdateapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app
      - ~/.aspnet/https:/https:ro