version: '3.4'

services:
  myapp:
    image: dualjobdateapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app
      - ~/.aspnet/https:/https:ro
